name: sourcecorp_flutter_app
description: A Flutter leave management application for Sourcecorp CRM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  cookie_jar: ^4.0.8
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

